version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
  kafka:
    image: apache/kafka-native
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9091:9091"
    #KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
    #KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
    #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

    # Settings required for KRaft mode
    #KAFKA_NODE_ID: 1
    #KAFKA_PROCESS_ROLES: broker,controller
    #KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    #KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

    # Listener to use for broker-to-broker communication
    #KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

    # Required for a single node cluster
    #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  
  api:
    build: .
    ports:
      # local->container
      - 3000:3000
    env_file:
      - .env
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017/dockerpostdatabase
      #DB_NAME: docker_post_database
      #KAFKA_BROKER: kafka:9092
    depends_on: 
      - mongo_db
      - kafka

volumes:
  mongo_data: {}